{{- if .Values.openbrain.db.persistentVolumeClaim.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "dlvy-open-brain.fullname" . }}-db-pv
  labels:
  {{- include "dlvy-open-brain.labels" . | nindent 4 }}
spec:
  capacity:
    storage: {{ .Values.openbrain.db.persistentVolumeClaim.size }}
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain  # If set as "Delete" container would be removed after pvc deletion
  storageClassName: azureblob-nfs-premium
  mountOptions:
    - nconnect=4
  csi:
    driver: blob.csi.azure.com
    volumeHandle: {{ .Values.openbrain.db.persistentVolumeClaim.storageAccount }}_{{ .Values.openbrain.db.persistentVolumeClaim.shareName }}
    volumeAttributes:
      containerName: {{ .Values.openbrain.db.persistentVolumeClaim.shareName }}
      storageAccount: {{ .Values.openbrain.db.persistentVolumeClaim.storageAccount }}
      resourceGroup: {{ .Values.openbrain.db.persistentVolumeClaim.resourceGroup }}
      protocol: nfs
{{- end }}
