{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  labels:
    {{- include "dlvy-open-brain.labels" . | nindent 4 }}
  annotations:
    azure.workload.identity/client-id: {{ .Values.workloadIdentity.clientId }}
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
